//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendMailAPI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GagaMobiAPI.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection not found..
        /// </summary>
        public static string DisconnectMsg_EN {
            get {
                return ResourceManager.GetString("DisconnectMsg_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถเชื่อมต่อได้.
        /// </summary>
        public static string DisconnectMsg_TH {
            get {
                return ResourceManager.GetString("DisconnectMsg_TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication fail..
        /// </summary>
        public static string MsgAutherized_EN {
            get {
                return ResourceManager.GetString("MsgAutherized_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระบบไม่มีสิทธิในการเข้าถึงข้อมูล.
        /// </summary>
        public static string MsgAutherized_TH {
            get {
                return ResourceManager.GetString("MsgAutherized_TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not changed dealers..
        /// </summary>
        public static string MsgChangeDealer_null_EN {
            get {
                return ResourceManager.GetString("MsgChangeDealer_null_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ท่านยังไม่ได้เปลี่ยนผู้แทนจำหน่าย.
        /// </summary>
        public static string MsgChangeDealer_null_TH {
            get {
                return ResourceManager.GetString("MsgChangeDealer_null_TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not change dealer..
        /// </summary>
        public static string MsgChangeDupDealer_EN {
            get {
                return ResourceManager.GetString("MsgChangeDupDealer_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถเปลี่ยน showroom ซ้ำได้.
        /// </summary>
        public static string MsgChangeDupDealer_TH {
            get {
                return ResourceManager.GetString("MsgChangeDupDealer_TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สำเร็จ.
        /// </summary>
        public static string MsgDeleteCarFail {
            get {
                return ResourceManager.GetString("MsgDeleteCarFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please waiting for contact..
        /// </summary>
        public static string MsgDeleteCarFailEN {
            get {
                return ResourceManager.GetString("MsgDeleteCarFailEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สำเร็จ.
        /// </summary>
        public static string MsgDeleteCarSuccess {
            get {
                return ResourceManager.GetString("MsgDeleteCarSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string MsgDeleteCarSuccessEN {
            get {
                return ResourceManager.GetString("MsgDeleteCarSuccessEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceeded file size..
        /// </summary>
        public static string MsgDocSizeLimit_EN {
            get {
                return ResourceManager.GetString("MsgDocSizeLimit_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขนาดไฟล์เกินกำหนด.
        /// </summary>
        public static string MsgDocSizeLimit_TH {
            get {
                return ResourceManager.GetString("MsgDocSizeLimit_TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ท่านไม่สามารถขอสินเชื่อออนไลน์ได้ เนื่องจากข้อมูลบัตรประชาชนไม่ถูกต้อง.
        /// </summary>
        public static string MsgDOPAOver3 {
            get {
                return ResourceManager.GetString("MsgDOPAOver3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you cannot apply online car loan because of invalid ID card informations..
        /// </summary>
        public static string MsgDOPAOver3EN {
            get {
                return ResourceManager.GetString("MsgDOPAOver3EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พบข้อผิดพลาด กรุณาติดต่อผู้เกี่ยวข้องเพื่อตรวจสอบ *2.
        /// </summary>
        public static string MsgError {
            get {
                return ResourceManager.GetString("MsgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, please contact to developer *2.
        /// </summary>
        public static string MsgError_EN {
            get {
                return ResourceManager.GetString("MsgError_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PIN Code.
        /// </summary>
        public static string MsgErrorPIN_EN {
            get {
                return ResourceManager.GetString("MsgErrorPIN_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณกรอกรหัสผิด.
        /// </summary>
        public static string MsgErrorPIN_TH {
            get {
                return ResourceManager.GetString("MsgErrorPIN_TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พบข้อผิดพลาด กรุณาติดต่อผู้เกี่ยวข้องเพื่อตรวจสอบ *1.
        /// </summary>
        public static string MsgInvalid {
            get {
                return ResourceManager.GetString("MsgInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid *1.
        /// </summary>
        public static string MsgInvalid_EN {
            get {
                return ResourceManager.GetString("MsgInvalid_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data mobile number.
        /// </summary>
        public static string MsgNoPhone_EN {
            get {
                return ResourceManager.GetString("MsgNoPhone_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบข้อมูลเบอร์โทรศัพท์.
        /// </summary>
        public static string MsgNoPhone_TH {
            get {
                return ResourceManager.GetString("MsgNoPhone_TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบข้อมูล QR Code นี้.
        /// </summary>
        public static string MsgPDF_Expire_EN {
            get {
                return ResourceManager.GetString("MsgPDF_Expire_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found QR Code..
        /// </summary>
        public static string MsgPDF_Expire_TH {
            get {
                return ResourceManager.GetString("MsgPDF_Expire_TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทำการเก็บข้อมูลเรียบร้อย.
        /// </summary>
        public static string MsgSuccess {
            get {
                return ResourceManager.GetString("MsgSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update data success..
        /// </summary>
        public static string MsgSuccess_EN {
            get {
                return ResourceManager.GetString("MsgSuccess_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&quot;WSStatus&quot;:&quot;Y&quot;, &quot;WSMsg&quot;: { &quot;Msgstatus&quot;:&quot;access denied&quot;,&quot;Result&quot; :&quot;&quot;, &quot;Rslc&quot; : &quot;{0}&quot;, &quot;Step&quot;: &quot;{1}&quot;,  &quot;Msgdesc_th&quot;: &quot;{2}&quot; ,&quot;Msgdesc_en&quot;: &quot;{3}&quot;  )).
        /// </summary>
        public static string respAccessDenied {
            get {
                return ResourceManager.GetString("respAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&quot;WSStatus&quot;:&quot;Y&quot;, &quot;WSMsg&quot;: ( &quot;Msgstatus&quot;:&quot;device logon&quot;, &quot;Result&quot; : &quot;&quot;, &quot;Rslc&quot; : &quot;{0}&quot;, &quot;Step&quot;: &quot;{1}&quot;, &quot;Msgdesc_th&quot;: &quot;{2}&quot; ,&quot;Msgdesc_en&quot;: &quot;{3}&quot;  )).
        /// </summary>
        public static string respDeviceLogOn {
            get {
                return ResourceManager.GetString("respDeviceLogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&quot;WSStatus&quot;:&quot;Y&quot;, &quot;WSMsg&quot;: ( &quot;Msgstatus&quot;:&quot;disable&quot;, &quot;Result&quot; : &quot;&quot;, &quot;Rslc&quot; : &quot;{0}&quot;, &quot;Step&quot;: &quot;{1}&quot;, &quot;Msgdesc_th&quot;: &quot;{2}&quot; ,&quot;Msgdesc_en&quot;: &quot;{3}&quot;  )).
        /// </summary>
        public static string respDisable {
            get {
                return ResourceManager.GetString("respDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&quot;STATUS&quot;: &quot;N&quot;,&quot;COUNT&quot; : &quot;{0}&quot;,&quot;DOPA_DESC_TH&quot; : &quot;{1}&quot;,&quot;DOPA_DESC_EN&quot; : &quot;{2}&quot;,&quot;REF_ID&quot;: &quot;{3}&quot;).
        /// </summary>
        public static string respDOPAFail {
            get {
                return ResourceManager.GetString("respDOPAFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&quot;STATUS&quot;: &quot;Y&quot;,&quot;COUNT&quot; : &quot;{0}&quot;,&quot;DOPA_DESC_TH&quot; : &quot;{1}&quot;,&quot;DOPA_DESC_EN&quot; : &quot;{2}&quot;,&quot;REF_ID&quot;: &quot;{3}&quot;).
        /// </summary>
        public static string respDOPASuccess {
            get {
                return ResourceManager.GetString("respDOPASuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&quot;WSStatus&quot;:&quot;N&quot;, &quot;WSMsg&quot;: ( &quot;Msgstatus&quot;:&quot;error&quot;, &quot;Result&quot; : &quot;&quot;, &quot;Rslc&quot; : &quot;{0}&quot;, &quot;Step&quot;: &quot;{1}&quot;, &quot;Msgdesc_th&quot;: &quot;{2}&quot; ,&quot;Msgdesc_en&quot;: &quot;{3}&quot;  )).
        /// </summary>
        public static string respError {
            get {
                return ResourceManager.GetString("respError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&quot;WSStatus&quot;:&quot;Y&quot;, &quot;WSMsg&quot;: ( &quot;Msgstatus&quot;:&quot;error&quot;, &quot;Result&quot; : &quot;&quot;, &quot;Rslc&quot; : &quot;{0}&quot;, &quot;Step&quot;: &quot;{1}&quot;,  &quot;Msgdesc_th&quot;: &quot;{2}&quot; ,&quot;Msgdesc_en&quot;: &quot;{3}&quot;  )).
        /// </summary>
        public static string respErrorFunc {
            get {
                return ResourceManager.GetString("respErrorFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&quot;WSStatus&quot;:&quot;Y&quot;, &quot;WSMsg&quot;: ( &quot;Msgstatus&quot;:&quot;invalid&quot;, &quot;Result&quot; : &quot;&quot;, &quot;Rslc&quot; : &quot;{0}&quot;, &quot;Step&quot;: &quot;{1}&quot;,  &quot;Msgdesc_th&quot;: &quot;{2}&quot; ,&quot;Msgdesc_en&quot;: &quot;{3}&quot;  )).
        /// </summary>
        public static string respInvalid {
            get {
                return ResourceManager.GetString("respInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&quot;STATUS&quot;:&quot;{0}&quot;, &quot;REF_ID&quot;:&quot;{1}&quot;, &quot;REF_URL&quot;: &quot;{2}&quot;).
        /// </summary>
        public static string respStep {
            get {
                return ResourceManager.GetString("respStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&quot;WSStatus&quot;:&quot;Y&quot;, &quot;WSMsg&quot;: (&quot;Msgstatus&quot; : &quot;{0}&quot; , &quot;Result&quot;:&quot;{1}&quot;, &quot;Rslc&quot;:&quot;{2}&quot;, &quot;Step&quot;: &quot;{3}&quot;,  &quot;Msgdesc_th&quot;: &quot;{4}&quot; ,&quot;Msgdesc_en&quot;: &quot;{5}&quot;  )).
        /// </summary>
        public static string respSuccess {
            get {
                return ResourceManager.GetString("respSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (c11)&quot;WSStatus&quot;:&quot;Y&quot;, &quot;WSMsg&quot;: (c11)&quot;Msgstatus&quot; : &quot;{0}&quot; , &quot;Result&quot;:{1}, &quot;Rslc&quot;:&quot;{2}&quot;, &quot;Step&quot;: &quot;{3}&quot;,  &quot;Msgdesc_th&quot;: &quot;{4}&quot; ,&quot;Msgdesc_en&quot;: &quot;{5}&quot;  (c12)(c12).
        /// </summary>
        public static string respSuccessDResult {
            get {
                return ResourceManager.GetString("respSuccessDResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&quot;WSStatus&quot;:&quot;Y&quot;, &quot;WSMsg&quot;: (&quot;Msgstatus&quot; : &quot;{0}&quot; , &quot;Result&quot;:{1}, &quot;Rslc&quot;:&quot;{2}&quot;, &quot;Step&quot;: &quot;{3}&quot;, &quot;Msgdesc_th&quot;: &quot;{4}&quot; ,&quot;Msgdesc_en&quot;: &quot;{5}&quot;  )).
        /// </summary>
        public static string respSuccessSync {
            get {
                return ResourceManager.GetString("respSuccessSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&quot;WSStatus&quot;:&quot;Y&quot;, &quot;WSMsg&quot;: (&quot;Msgstatus&quot; : &quot;{0}&quot; , &quot;Result&quot;:{1}, &quot;Rslc&quot;:&quot;{2}&quot;, &quot;Step&quot;: &quot;{3}&quot;,  &quot;Msgdesc_th&quot;: &quot;{4}&quot; ,&quot;Msgdesc_en&quot;: &quot;{5}&quot;  )).
        /// </summary>
        public static string respSuccessWithDS {
            get {
                return ResourceManager.GetString("respSuccessWithDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload required document..
        /// </summary>
        public static string SubmitDocRequire_EN {
            get {
                return ResourceManager.GetString("SubmitDocRequire_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ท่านยังไม่ได้อัพโหลดเอกสารที่จำเป็น.
        /// </summary>
        public static string SubmitDocRequire_TH {
            get {
                return ResourceManager.GetString("SubmitDocRequire_TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        public static string typeError {
            get {
                return ResourceManager.GetString("typeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid.
        /// </summary>
        public static string typeInvalid {
            get {
                return ResourceManager.GetString("typeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to success.
        /// </summary>
        public static string typeSuccess {
            get {
                return ResourceManager.GetString("typeSuccess", resourceCulture);
            }
        }
    }
}
